"""symptom survives daily_entry and pain_profile deletion, sleep is_nap

Revision ID: 1a93daa43d13
Revises: 3a0c79f82fb0
Create Date: 2026-09-10 10:55:35.879483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a93daa43d13'
down_revision: Union[str, None] = '3a0c79f82fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here: existing sleep rows need a value the
    # moment the column appears, before any backfill runs. It matches the
    # model's client-side default=False, so no separate backfill step exists to
    # drop it after (see also: this project has real logged data to preserve).
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_nap', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.alter_column('daily_entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_symptom_daily_entry_id_daily_entry', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_symptom_daily_entry_id_daily_entry'), 'daily_entry', ['daily_entry_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_symptom_daily_entry_id_daily_entry'), type_='foreignkey')
        batch_op.create_foreign_key('fk_symptom_daily_entry_id_daily_entry', 'daily_entry', ['daily_entry_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('daily_entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.drop_column('is_nap')

    # ### end Alembic commands ###
