"""initial schema

Revision ID: 3a0c79f82fb0
Revises: 
Create Date: 2026-09-06 17:40:22.170961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0c79f82fb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sport', sa.String(length=60), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete'))
    )
    op.create_table('athlete_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('current_weekly_mileage', sa.Float(), nullable=True),
    sa.Column('peak_weekly_mileage', sa.Float(), nullable=True),
    sa.Column('current_training_phase', sa.String(length=30), nullable=True),
    sa.Column('baseline_protein_g', sa.Float(), nullable=True),
    sa.Column('baseline_carbs_g', sa.Float(), nullable=True),
    sa.Column('baseline_fat_g', sa.Float(), nullable=True),
    sa.Column('baseline_calories', sa.Float(), nullable=True),
    sa.Column('baseline_sleep_hours', sa.Float(), nullable=True),
    sa.Column('injury_history', sa.JSON(), nullable=True),
    sa.Column('preferred_recovery_methods', sa.JSON(), nullable=True),
    sa.Column('stress_response_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_athlete_profile_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_profile'))
    )
    with op.batch_alter_table('athlete_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_profile_athlete_id'), ['athlete_id'], unique=True)

    op.create_table('body_part_vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('body_location', sa.String(length=60), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('recurrence_risk', sa.String(length=20), nullable=True),
    sa.Column('average_duration_days', sa.Float(), nullable=True),
    sa.Column('common_triggers', sa.JSON(), nullable=True),
    sa.Column('effective_methods', sa.JSON(), nullable=True),
    sa.Column('days_since_last_episode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_body_part_vulnerability_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_part_vulnerability')),
    sa.UniqueConstraint('athlete_id', 'body_location', name='uq_body_part_vulnerability_athlete_location')
    )
    with op.batch_alter_table('body_part_vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_part_vulnerability_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('daily_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('nutrition_score', sa.Float(), nullable=True),
    sa.Column('training_load_normalized', sa.Float(), nullable=True),
    sa.Column('recovery_daily_score', sa.Float(), nullable=True),
    sa.Column('symptom_severity', sa.Float(), nullable=True),
    sa.Column('daily_load', sa.Float(), nullable=True),
    sa.Column('load_7d', sa.Float(), nullable=True),
    sa.Column('load_28d', sa.Float(), nullable=True),
    sa.Column('acute_chronic_ratio', sa.Float(), nullable=True),
    sa.Column('recovery_volume_7d', sa.Float(), nullable=True),
    sa.Column('recovery_adequacy', sa.Float(), nullable=True),
    sa.Column('recovery_shortfall', sa.Float(), nullable=True),
    sa.Column('training_phase', sa.String(length=30), nullable=True),
    sa.Column('in_stress_period', sa.Boolean(), nullable=True),
    sa.Column('within_stress_pattern', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_terms', sa.JSON(), nullable=True),
    sa.Column('hard_limits_triggered', sa.JSON(), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_daily_entry_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_entry')),
    sa.UniqueConstraint('athlete_id', 'date', name='uq_daily_entry_athlete_date')
    )
    with op.batch_alter_table('daily_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_entry_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_entry_date'), ['date'], unique=False)

    op.create_table('lifestyle_commitment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('workload_intensity_1_to_10', sa.Integer(), nullable=True),
    sa.Column('term_start_date', sa.Date(), nullable=True),
    sa.Column('term_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_lifestyle_commitment_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lifestyle_commitment'))
    )
    with op.batch_alter_table('lifestyle_commitment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifestyle_commitment_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('days_of_data', sa.Integer(), nullable=True),
    sa.Column('stress_instances_observed', sa.Integer(), nullable=True),
    sa.Column('variance_score', sa.Float(), nullable=True),
    sa.Column('calibration_offset', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('per_method_efficacy', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_model_metrics_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_metrics'))
    )
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_metrics_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metrics_date'), ['date'], unique=False)

    op.create_table('pain_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('body_location', sa.String(length=60), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('max_intensity_1_to_10', sa.Integer(), nullable=True),
    sa.Column('type_progression', sa.JSON(), nullable=True),
    sa.Column('concurrent_conditions', sa.JSON(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('effective_recovery_methods', sa.JSON(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_pain_profile_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pain_profile'))
    )
    with op.batch_alter_table('pain_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pain_profile_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pain_profile_body_location'), ['body_location'], unique=False)

    op.create_table('prediction_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('predicted_risk', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('outcome_location', sa.String(length=60), nullable=True),
    sa.Column('outcome_duration_days', sa.Integer(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('athlete_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_prediction_accuracy_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_accuracy'))
    )
    with op.batch_alter_table('prediction_accuracy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_accuracy_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_accuracy_prediction_date'), ['prediction_date'], unique=False)

    op.create_table('stress_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expected_intensity_1_to_10', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_stress_event_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stress_event'))
    )
    with op.batch_alter_table('stress_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stress_event_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('training_phase', sa.String(length=30), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('meals', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('recall_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_nutrition_athlete_id_athlete'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entry.id'], name=op.f('fk_nutrition_daily_entry_id_daily_entry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition'))
    )
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_daily_entry_id'), ['daily_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nutrition_date'), ['date'], unique=False)

    op.create_table('sleep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('quality_1_to_10', sa.Integer(), nullable=True),
    sa.Column('bedtime', sa.Time(), nullable=True),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('recall_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_sleep_athlete_id_athlete'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entry.id'], name=op.f('fk_sleep_daily_entry_id_daily_entry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sleep'))
    )
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_daily_entry_id'), ['daily_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_date'), ['date'], unique=False)

    op.create_table('symptom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('body_location', sa.String(length=60), nullable=False),
    sa.Column('intensity_1_to_10', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('onset', sa.String(length=20), nullable=True),
    sa.Column('limiting', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('pain_profile_id', sa.Integer(), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('recall_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_symptom_athlete_id_athlete'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entry.id'], name=op.f('fk_symptom_daily_entry_id_daily_entry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pain_profile_id'], ['pain_profile.id'], name=op.f('fk_symptom_pain_profile_id_pain_profile'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom'))
    )
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_body_location'), ['body_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_daily_entry_id'), ['daily_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_pain_profile_id'), ['pain_profile_id'], unique=False)

    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('intensity_1_to_10', sa.Integer(), nullable=True),
    sa.Column('intensity_factor', sa.Float(), nullable=True),
    sa.Column('elevation_gain_ft', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('recall_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_training_athlete_id_athlete'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entry.id'], name=op.f('fk_training_daily_entry_id_daily_entry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training'))
    )
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_daily_entry_id'), ['daily_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_date'), ['date'], unique=False)

    op.create_table('recovery_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('method_type', sa.String(length=40), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('intensity_1_to_10', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.Time(), nullable=True),
    sa.Column('symptom_id', sa.Integer(), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('recall_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_recovery_method_athlete_id_athlete'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entry.id'], name=op.f('fk_recovery_method_daily_entry_id_daily_entry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptom.id'], name=op.f('fk_recovery_method_symptom_id_symptom'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_method'))
    )
    with op.batch_alter_table('recovery_method', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_method_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_method_daily_entry_id'), ['daily_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_method_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_method_symptom_id'), ['symptom_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_method', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_method_symptom_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_method_date'))
        batch_op.drop_index(batch_op.f('ix_recovery_method_daily_entry_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_method_athlete_id'))

    op.drop_table('recovery_method')
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_date'))
        batch_op.drop_index(batch_op.f('ix_training_daily_entry_id'))
        batch_op.drop_index(batch_op.f('ix_training_athlete_id'))

    op.drop_table('training')
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_pain_profile_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_date'))
        batch_op.drop_index(batch_op.f('ix_symptom_daily_entry_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_body_location'))
        batch_op.drop_index(batch_op.f('ix_symptom_athlete_id'))

    op.drop_table('symptom')
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_date'))
        batch_op.drop_index(batch_op.f('ix_sleep_daily_entry_id'))
        batch_op.drop_index(batch_op.f('ix_sleep_athlete_id'))

    op.drop_table('sleep')
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_date'))
        batch_op.drop_index(batch_op.f('ix_nutrition_daily_entry_id'))
        batch_op.drop_index(batch_op.f('ix_nutrition_athlete_id'))

    op.drop_table('nutrition')
    with op.batch_alter_table('stress_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stress_event_athlete_id'))

    op.drop_table('stress_event')
    with op.batch_alter_table('prediction_accuracy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_accuracy_prediction_date'))
        batch_op.drop_index(batch_op.f('ix_prediction_accuracy_athlete_id'))

    op.drop_table('prediction_accuracy')
    with op.batch_alter_table('pain_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pain_profile_body_location'))
        batch_op.drop_index(batch_op.f('ix_pain_profile_athlete_id'))

    op.drop_table('pain_profile')
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_metrics_date'))
        batch_op.drop_index(batch_op.f('ix_model_metrics_athlete_id'))

    op.drop_table('model_metrics')
    with op.batch_alter_table('lifestyle_commitment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifestyle_commitment_athlete_id'))

    op.drop_table('lifestyle_commitment')
    with op.batch_alter_table('daily_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_entry_date'))
        batch_op.drop_index(batch_op.f('ix_daily_entry_athlete_id'))

    op.drop_table('daily_entry')
    with op.batch_alter_table('body_part_vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_part_vulnerability_athlete_id'))

    op.drop_table('body_part_vulnerability')
    with op.batch_alter_table('athlete_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_profile_athlete_id'))

    op.drop_table('athlete_profile')
    op.drop_table('athlete')
    # ### end Alembic commands ###
