"""daily_entry no_pain_confirmed

Revision ID: ee415a110068
Revises: 1a93daa43d13
Create Date: 2026-09-10 19:28:40.272276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee415a110068'
down_revision: Union[str, None] = '1a93daa43d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_pain_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_entry', schema=None) as batch_op:
        batch_op.drop_column('no_pain_confirmed')

    # ### end Alembic commands ###
